name: Daily Instagram Story Fetcher

on:
  schedule:
    - cron: '30 0 * * *'  # Запуск каждый день в 00:30 UTC (~02:30 по Москве)
  workflow_dispatch:

jobs:
  download_stories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install instaloader python-telegram-bot dropbox

      - name: Restore Instagram session file from secret
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_SESSION: ${{ secrets.IG_SESSION }}
        run: |
          echo "$IG_SESSION" | base64 -d > "$IG_USERNAME.session"

      - name: Run story bot
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python story_bot.py
