name: Download Instagram Stories

on:
  workflow_dispatch:

jobs:
  download-stories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Instaloader
        run: pip install instaloader

      - name: Restore session file from secret
        run: echo "${{ secrets.IG_SESSION_B64 }}" | base64 -d > session-igor.smnv

      - name: Download Instagram stories
        run: instaloader --sessionfile=session-igor.smnv igor.smnv --stories --dirname-pattern=stories
